name: ppt-visual-taxonomy
version: 1.0.0
schema_version: 1
description: "Unified visual type classification system: 3-level taxonomy (Core/Extended/Domain), annotation standards, cognitive intent mapping, and placeholder data templates."
owner: ppt-content-planner, ppt-visual-designer
category: reference
tags:
  - ppt
  - visual-taxonomy
  - chart-types
  - diagram-types
dependencies: []
integration:
  agents:
    - ppt-content-planner
    - ppt-visual-designer
  skills: []
last_updated: 2026-02-07

# Reference to auxiliary files in the directory
readme: README.md
examples: examples.yml

# High-level outputs schema (machine-readable summary)
outputs:
  visual_type_selection:
    description: "Recommended visual type based on content and data structure."
    fields:
      visual_type: string
      taxonomy_level: string  # core | extended | domain-specific
      cognitive_intent: string
      data_requirement: string
      confidence: float
  visual_annotation:
    description: "Structured annotation for slides.md visual block."
    fields:
      visual_type: string
      placeholder_data: object
      validation_passed: bool
