name: ppt-design-system
version: 1.0.0
schema_version: 1
description: "Material Design 3 design system for PPT: tokens (color/typography/spacing), component library, layout templates, chart encoding, performance budgets, and quality checklist."
owner: ppt-visual-designer
category: reference
tags:
  - ppt
  - design-system
  - material-design
  - visual-design
dependencies: []
integration:
  agents:
    - ppt-visual-designer
  skills:
    - ppt-visual-taxonomy
last_updated: 2026-02-07

# Reference to auxiliary files in the directory
readme: README.md
examples: examples.yml

# High-level outputs schema (machine-readable summary)
outputs:
  success:
    description: "design-spec.json created with Material Design-compliant slide specifications, passing all quality checks."
    fields:
      slides_count: int
      components_used: [string]
      performance_budget_ok: bool
      qa_checks_passed: int
      file_size_estimate_mb: float
  partial:
    description: "design-spec.json created but some quality checks or performance budgets failed."
    fields:
      slides_count: int
      qa_checks_passed: int
      qa_checks_failed: int
      warnings: [string]
      performance_violations: [string]
  error:
    description: "Unable to generate design-spec.json due to validation failure or missing input."
    fields:
      error_type: string
      message: string
